global:
  scrape_interval: 15s       # metrik çekme sıklığı
  evaluation_interval: 15s   # kural değerlendirme sıklığı

scrape_configs:

  # Prometheus'un kendi metrikleri
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Sunucu sistem metrikleri (CPU, RAM, Disk, Network)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']   # docker-compose servis adı
